### ISSUE TITLE
Artist link apple/itunes. Difference?

### ISSUE THREAD

**Issue by mr44er** [kellnerd/harmony#24]
Starting with https://www.deezer.com/fr/album/10882160 and harmony gives
`https://music.apple.com/gb/artist/505840851`

This leads to MB not autodetecting the service:
![Bildschirmfoto zu 2024-06-09 14-46-11](https://github.com/kellnerd/harmony/assets/46787531/8f7b352a-1cf6-42b9-babe-0bda29daf85b)

Correct for autodetection would be `https://itunes.apple.com/gb/artist/id505840851`
I don't know if these are two separated services or just URL redundancy for itunes. If it's the same service, changing the output URL via harmony should easily fix it or is there some technical reason against?

For now I'll stick with the itunes link :)
https://musicbrainz.org/artist/2e21383f-f71e-4367-bfa8-5a02c74643a8

**Comment by kellnerd** [comment]
You should be adding music.apple.com links, itunes.apple.com is the legacy domain which nowadays redirects to music.apple.com.

Harmony will only use the new links to resolve MBIDs as most artists already have these and the rest should get them added or changed. Doing additional API requests for the old legacy format is just making lookups slower for almost no benefit.

That said, MB is autodetecting the link, it just asks you to select a link type because multiple combinations are possible (streaming, download) whereas old iTunes only supported one (download).

**Comment by mr44er** [comment]
Ah, ok. That fills missing info, thx.
