### ISSUE TITLE
doesn't add "purchase for download" Bandcamp links?

### ISSUE THREAD

**Issue by UltimateRiff** [kellnerd/harmony#44]
while importing this release, I noticed Harmony didn't add the purchase relationship to the Bandcamp URL. this should be happening, since the release is a "name your price" release

https://harmony.pulsewidth.org.uk/release?bandcamp=vyletpony%2Ftrack%2Fcreature-city-2&ts=1719021233

(this release is already imported [here](https://musicbrainz.org/release/3e5536b6-d3c8-47e0-97b5-91af826858ee), with the link manually added)

**Comment by kellnerd** [comment]
The current logic is quite simple, the provider only adds the free **or** the paid download link depending on the minimum price:
https://github.com/kellnerd/harmony/blob/23b7da23d2a1176f3fe5909dec031ded5cf0add9/providers/Bandcamp/mod.ts#L253-L257
Does it make sense to add both link types for "name your price" (since you can technically download it for free) or is this rather a paid only download where you can pay 0$?
I wonder if there is any download on Bandcamp you can not pay for and only get for free.

**Comment by kellnerd** [comment]
I have now made the logic for "paid download" and "free download" more independent in https://github.com/kellnerd/harmony/commit/536bc325b9967615ae630d569b1799229d4eb759 (currently only on my development branch), we will see if there are any releases which can be downloaded for free but not paid for.

**Comment by UltimateRiff** [comment]
there is in fact the option of only free downloads:

https://balloonparty.bandcamp.com/album/100-no-feeble-cheering

**Comment by kellnerd** [comment]
Cool, thanks for the example, so free downloads also work as expected with my new logic.
