### ISSUE TITLE
Deno 2.0 TypeError running locally 

### ISSUE THREAD

**Issue by donovanallen** [kellnerd/harmony#66]
I'm running into the following error when trying to run this locally. On latest Deno version. I'm getting the same error on running any of the Deno tasks. I've tried to do some investigating, but not totally familiar with Deno. 

Thanks in advance!

`harmony % deno task dev
Task dev deno run -A --watch=server/static/,server/routes/ server/dev.ts
Watcher Process started.
The manifest has been generated for 6 routes and 2 islands.
error: Uncaught (in promise) TypeError: Deno.seekSync is not a function
      Deno.seekSync(rid, offset, Deno.SeekMode.Start);
           ^
    at js_read (https://deno.land/x/sqlite@v3.8/build/vfs.js:48:12)
    at <anonymous> (wasm://wasm/0028679a:1:5898)
    at <anonymous> (wasm://wasm/0028679a:1:146166)
    at <anonymous> (wasm://wasm/0028679a:1:141310)
    at <anonymous> (wasm://wasm/0028679a:1:147518)
    at <anonymous> (wasm://wasm/0028679a:1:3869)
    at <anonymous> (wasm://wasm/0028679a:1:611986)
    at https://deno.land/x/sqlite@v3.8/src/db.ts:208:27
    at setStr (https://deno.land/x/sqlite@v3.8/src/wasm.ts:19:20)
    at new DB (https://deno.land/x/sqlite@v3.8/src/db.ts:205:20)`

**Comment by kellnerd** [comment]
Ah, this looks like it is related to the recent Deno 2.0 release, which includes some breaking changes.
I'm still on the previous Deno version 1.46, so I haven't noticed this issue so far.

But since I've followed the Deno 2.0 (pre-)announcements, I doubt that Harmony's code itself needs updating. Judging by the error message, the external sqlite package version 3.8 seems to be incompatible. There have been [new releases](https://github.com/dyedgreen/deno-sqlite/releases) (3.9.0 and 3.9.1) which look like they should fix the issue.

Do you want to try upgrading the dependency and testing the new version yourself?
If not, I can update Deno to 2.0 on one of my machines and have a try myself.

**Comment by kellnerd** [comment]
Ah sorry, I just realized that the sqlite package is not actually used here, it is only an indirect dependency. I will fix this in https://github.com/kellnerd/snap_storage

**Comment by donovanallen** [comment]
I pulled down dev and that seems to be working for me with Deno 2.x. Thank you so much. I'll keep an eye out for updates to main.

**Comment by kellnerd** [comment]
I've successfully tested Harmony with Deno 2.0 myself and forwarded the changes from my dev branch to main.
